[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python-intermediate-inflammation"
version = "0.0.0"
requires-python = ">=3.9"
description = "A Python data management system that manages trial data used in clinical inflammation studies."
readme = "README.md"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocstrings[python]>=0.30.1",
    "ruff>=0.14.5",
]

[tool.setuptools]
packages = ["inflammation"]

[tool.ruff.lint]
select = ["E", "W", "F", "UP", "A", "B", "SIM", "I"]
